[package]
name = "oxideproc"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
cuda-core = "=0.3.1"
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "6abfaa091e29a6275c1943895bfbc97efa306e98" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "6abfaa091e29a6275c1943895bfbc97efa306e98" }
